<?php

session_start();
 include('head.php');
?>



<!-- <nav class="breadcrumb" aria-label="breadcrumbs">

        <div class="container-bg">

          <h1>Terms of Use</h1>

          <a href="index.php" title="Back to the frontpage">Home</a>



          <span aria-hidden="true" class="breadcrumb__sep">&#47;</span>

          <span>Terms of Use</span>

        </div>

      </nav> -->



      <main class="main-content" style="width: 95%;
    margin: 2%;">

        <div class="dt-sc-hr-invisible-small"></div>
    <h2 style="text-align:center">Terms of Use</h2>
    <hr><br>
    
    

<p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there
under as applicable and the amended provisions pertaining to electronic records in various statutes
as amended by the Information Technology Act, 2000. This electronic record is generated by a
computer system and does not require any physical or digital signatures.</p>

<p>
This document is published in accordance with the provisions of Rule 3 (1) of the Information
Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations,
privacy policy and Terms of Use for access or usage of domain name [www.allmart.world]
(“Website”), including the related mobile site and mobile application (hereinafter referred to as
“Platform”)
</p>

<p>
    

The Platform is owned by Allmart Ecommerce LLP a company incorporated under the Limited
Liability Partnership Act, 2008 with its registered office at- MHB Colony no. 1, Flat no. 2, Near
Dhanukarwadi, Mahavir Nagar, Kandivali (West), Mumbai 400067. Maharashtra. India. (hereinafter
referred to as "Allmart").</p>

<p>
    

Your use of the Platform and services and tools are governed by the following terms and conditions
("Terms of Use") as applicable to the Platform including the applicable policies which are
incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the
policies that are applicable to the Platform for such transaction. By mere use of the Platform, You
shall be contracting with Allmart Ecommerce LLP and these terms and conditions including the
policies constitute Your binding obligations, with Allmart.
</p>


<p>
    
For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean
any natural or legal person who has agreed to become a buyer on the Platform by providing
Registration Data while registering on the Platform as Registered User using the computer systems.
Allmart allows the User to surf the Platform or make purchases without registering on the Platform.
The term "We", "Us", "Our" shall mean Allmart Ecommerce LLP.</p>


<p>
    

When You use any of the services provided by Us through the Platform, including but not limited to,
(e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms,
and conditions applicable to such service, and they shall be deemed to be incorporated into this
Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right,
at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time
without any prior written notice to You. It is Your responsibility to review these Terms of Use
periodically for updates / changes. Your continued use of the Platform following the posting of
changes will mean that You accept and agree to the revisions. As long as You comply with these
Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter
and use the Platform.</p>


<p>
    

ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT
TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ
THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting
these Terms of Use, You also accept and agree to be bound by Allmart Policies ((including but not
limited to Privacy Policy available at Privacy) as amended from time to time.
</p>



<strong>Membership Eligibility</strong>

<p>
    Transaction on the Platform is available only to persons who can form legally binding contracts
under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of
the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the
Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access
content on the Platform only under the supervision and prior consent/ permission of a parent or legal
guardian.
</p>


<p>
    

As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by
your legal guardian or parents. Allmart reserves the right to terminate your membership and / or
refuse to provide you with access to the Platform if it is brought to Allmart's notice or if it is
discovered that You are under the age of 18 years and transacting on the Platform.</p>

<strong>
Your Account and Registration Obligations    
</strong>
<p>
    

If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display
Name and Password and You shall be responsible for all activities that occur under your Display
Name and Password. You agree that if You provide any information that is untrue, inaccurate, not
current or incomplete or We have reasonable grounds to suspect that such information is untrue,
inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have
the right to indefinitely suspend or terminate or block access of your membership on the Platform
and refuse to provide You with access to the Platform.
</p>


<p>
    
Your mobile phone number and/or e-mail address is treated as Your primary identifier on the
Platform. It is your responsibility to ensure that Your mobile phone number and your email address is
up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number
or e-mail address changes by updating the same on the Platform through a one time password
verification.</p>

<p>
    

You agree that Allmart shall not be liable or responsible for the activities or consequences of use or
misuse of any information that occurs under your Account in cases, including, where You have failed
to update Your revised mobile phone number and/or e-mail address on the Website Platform.</p>


<p>
    
If You share or allow others to have access to Your account on the Platform (“Account”), by creating
separate profiles under Your Account, or otherwise, they will be able to view and access Your
Account information. You shall be solely liable and responsible for all the activities undertaken under
Your Account, and any consequences therefrom. </p>



<strong>Communications</strong>

<p>
    
When You use the Platform or send emails or other data, information or communication to us, You
agree and understand that You are communicating with Us through electronic records and You
consent to receive communications via electronic records from Us periodically and as and when
required. We may communicate with you by email or by such other modes of communication,
electronic or otherwise.</p>


<strong>Platform for Transaction and Communication</strong>

<p>
    
The Platform is a platform that Users utilize to meet and interact with one another for their
transactions. Allmart is not and cannot be a party to or control in any manner any transaction
between the Platform's Users.</p>


<p>Henceforward:</p>
<ul>
    <li>
        All commercial/contractual terms are offered by and agreed to between Buyers and Sellers
alone. The commercial/contractual terms include without limitation price, shipping costs,
payment methods, payment terms, date, period and mode of delivery, warranties related to
products and services and after sales services related to products and services. Allmart
does not have any control or does not determine or advise or in any way involve itself in the
offering or acceptance of such commercial/contractual terms between the Buyers and
Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not by
Allmart.
        
    </li>
    
    <li>
Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in
the order by the Buyer to the Seller and it shall not be construed as Seller's acceptance of
Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such
order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same
by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by
Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the
quantities exceed the typical individual consumption. This applies both to the number of
products ordered within a single order and the placing of several orders for the same
product where the individual orders comprise a quantity that exceeds the typical individual
consumption. What comprises a typical individual's consumption quantity limit shall be
based on various factors and at the sole discretion of the Seller and may vary from
individual to individual.        
    </li>
    
    <li>
        Allmart does not make any representation or Warranty as to specifics (such as quality, value,
salability, etc) of the products or services proposed to be sold or offered to be sold or
purchased on the Platform. Allmart does not implicitly or explicitly support or endorse the
sale or purchase of any products or services on the Platform. Allmart accepts no liability for
any errors or omissions, whether on behalf of itself or third parties.
        
    </li>
    
    <li>
        Allmart is not responsible for any non-performance or breach of any contract entered into
between Buyers and Sellers. Allmart cannot and does not guarantee that the concerned
Buyers and/or Sellers will perform any transaction concluded on the Platform. Allmart shall
not and is not required to mediate or resolve any dispute or disagreement between Buyers
and Sellers.
    </li>
    
    <li>
        Allmart does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Platform and use Your best judgment in that behalf.
    </li>
    
    <li>
        Allmart does not at any point of time during any transaction between Buyer and Seller on the Platform come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer.
    </li>
    
    <li>
        At no time shall Allmart hold any right, title or interest over the products nor shall Allmart
have any obligations or liabilities in respect of such contract entered into between Buyers
and Sellers. Allmart is not responsible for unsatisfactory or delayed performance of services
or damages or delays as a result of products which are out of stock, unavailable or back
ordered.
    </li>
    
    <li>
  The Platform is only a platform that can be utilized by Users to reach a larger base to buy
and sell products or services. Allmart is only providing a platform for communication and it is
agreed that the contract for sale of any of the products or services shall be a strictly bipartite
contract between the Seller and the Buyer.</li>

</ul>



<p>
    
At no time shall Allmart hold any right, title or interest over the products nor shall Allmart have any obligations or liabilities in respect of such contract.
</p>


<p>
    
Allmart is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.</p>

<p>
    Select products offered by sellers may be eligible for business purchases on the Platform.
</p>      
    
    <ul>
        

    <li>
  Upon Your purchase of product(s) eligible for business purchases, You may be able to avail the
benefits of GST input tax credit. Accordingly, at your request, an invoice containing the GSTIN
as provided by You ("Tax Invoice") shall be issued to You by the Seller(s) selling such products.      
        <ul>
            <li>
            GST invoice will have, inter alia, the following details printed on it: -GSTIN associated with
            your registered business, as provided by you      
            </li>
            
            <li>
            Entity name of your registered business, as provided by you.       
            </li>
            
            <li>
                Not all products are eligible for business purchases on the Platform and the same is solely
at the discretion of the Sellers. You will be able to view the eligibility of Tax Invoice on the
product page on the Platform.

            </li>
            
            <li>
                Purchases on the Platform must only be for end consumption. Users must not use products
purchased on the Platform for any commercial, promotional, resale or further distribution
purposes
            </li>
            
            <li>
                For seamless availment of input tax credit, kindly mention the delivery address as the
address which is mentioned as the registered place of business as per the records of GST
authority. Please note that availment of input tax credit is subject to provisions of GST Act
and rules.
            </li>
            
            <li>The delivery and billing addresses will be required to be the same, please note that input tax
credit will be denied by GST authority if the delivery address and GSTIN in the GST invoice
are of different states.
</li>

<li>
    If GSTIN and/or business entity details are not provided by You, it will be presumed that it is
a personal purchase and not a business purchase.
</li>

<li>
    Allmart is not responsible to verify the correctness of the GSTIN and/or entity name provided
by You and You shall be entirely responsible to provide the accurate details
</li>

<li>
    Allmart and Seller shall not entertain any request for any revision in the GST Invoice. Allmart
and Seller shall not be liable for Your default including for reasons associated with details
provided by You.

</li>

<li>
    Allmart will not be liable in case You are not able to avail input tax credit or if input tax credit
is denied to You for any reason whatsoever.
</li>

<li>
    You shall be solely liable for all compliances required under applicable laws.
</li>

<li>
    You agree to indemnify and hold Allmart and Seller harmless from all losses, claims, costs,
expenses, suits, proceedings, or any other liability including any third-party claims (including
any penalties imposed by governmental authorities) arising out of or in connection with (1)
the GSTIN and/or entity name provided by you or the input tax credit claimed by you or your
use or misuse of the GST Invoice and (2) your non-compliance with the applicable laws or
(3) your use or misuse of any third-party’s details including GSTIN.

</li>

<li>
    Allmart has the right to not allow business purchases on the Platform to You if a fraudulent
activity is identified.

</li>

<li>
    Seller reserves the right to not issue Tax Invoice or issue a credit note against an already
issued Tax Invoice to cancel the transaction, if any fraudulent activity is identified.
</li>
        </ul>
    

<li>
    You shall independently agree upon the manner and terms and conditions of delivery, payment,
insurance etc. with the seller(s) that You transact with.
</li>

<p>
    Disclaimer: Pricing on any product(s) as is reflected on the Platform may due to some technical
issue, typographical error or that the product information published by the seller may be incorrectly
reflected and in such an event the seller may cancel such your order(s).
</p>

<li>
    You release and indemnify Allmart and/or any of its officers and representatives from any cost,
damage, liability or other consequence of any of the actions of the Users of the Platform and
specifically waive any claims that you may have in this behalf under any applicable law.
</li>

<p>
    Notwithstanding its reasonable efforts in that behalf, Allmart cannot take responsibility or control
the information provided by other Users which is made available on the Platform. You may find
other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please
use caution and practice safe trading when using the Platform.
</p>


</ul>

<p>
    Please note that there could be risks in dealing with underage persons or people acting under false
pretence.

</p>


<br>

<strong>Charges</strong>

<p>Membership on the Platform is free for buyers. Allmart does not charge any fee for browsing and
buying on the Platform. Allmart reserves the right to change its Fee Policy from time to time. In
particular, Allmart may at its sole discretion introduce new services and modify some or all of the
existing services offered on the Platform. In such an event Allmart reserves the right to introduce
fees for the new services offered or amend/introduce fees for existing services, as the case may be.
Changes to the Fee Policy shall be posted on the Platform and such changes shall automatically
become effective immediately after they are posted on the Platform. Unless otherwise stated, all
fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all
applicable laws including those in India for making payments to Allmart Ecommerce LLP.</p>

<br>

<strong>Use of the Platform</strong>

<p>
    You agree, undertake and confirm that Your use of Platform shall be strictly governed by the
following binding principles:
</p>
<li>You shall not host, display, upload, modify, publish, transmit, update or share any
information which:</li>

<p>(a) belongs to another person and to which You does not have any right to;</p>

<p>(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic,
libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging,
relating or encouraging money laundering or gambling, or otherwise unlawful in any manner
whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent
representation of women" within the meaning of the Indecent Representation of Women (Prohibition)
Act, 1986;</p>


<p>(c) is misleading in any way; </p>

<p>(d) is patently offensive to the online community, such as sexually explicit content, or content that
promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any
group or individual;</p>


<p>
    (e) harasses or advocates harassment of another person;
</p>


<p>(f) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or
"spamming";</p>

<p>(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or
libellous; </p>


<p>(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property
rights, rights of privacy (including without limitation unauthorized disclosure of a person's name,
email address, physical address or phone number) or rights of publicity];</p>


<p>(i) promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright
complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material),
such as providing pirated computer programs or links to them, providing information to circumvent
manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;</p>

<p>
    (j) contains restricted or password-only access pages, or hidden pages or images (those not linked
to or from another accessible page);
</p>

<p>(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</p>

<p>(l) provides instructional information about illegal activities such as making or buying illegal weapons,
violating someone's privacy, or providing or creating computer viruses;</p>

<p>(m) contains video, photographs, or images of another person (with a minor or an adult).</p>

<p>(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to
profiles, blogs, communities, account information, bulletins, friend request, or other areas of the
Platform or solicits passwords or personal identifying information for commercial or unlawful
purposes from other users;
</p>

<p>
    (o) engages in commercial activities and/or sales without Our prior written consent such as contests,
sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products
related to the Platform. Throughout this Terms of Use, Allmart's prior written consent means a
communication coming from Allmart's Legal Department, specifically in response to Your request,
and specifically addressing the activity or conduct for which You seek authorization;
</p>

<p>(p) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is
or could be construed as being illegal;</p>

<p>
    (q) interferes with another USER's use and enjoyment of the Platform or any other individual's User
and enjoyment of similar services;
</p>


<p>(r) refers to any Platform or URL that, in Our sole discretion, contains material that is inappropriate
for the Platform or any other Platform, contains content that would be prohibited or violates the letter
or spirit of these Terms of Use.</p>

<p>
    (s) harm minors in any way;
</p>

<p>(t) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets
or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen
products;</p>

<p>
    (u) violates any law for the time being in force;
</p>

<p>(v) deceives or misleads the addressee/ users about the origin of such messages or communicates
any information which is grossly offensive or menacing in nature;</p>


<p>(w) impersonate another person;</p>

<p>(x) contains software viruses or any other computer code, files or programs designed to interrupt,
destroy or limit the functionality of any computer resource; or contains any trojan horses, worms,
time bombs, cancelbots, easter eggs or other computer programming routines that may damage,
detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system,
data or personal information;</p>

<p>(y) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with
foreign states, or public order or causes incitement to the commission of any cognizable offence or
prevents investigation of any offence or is insulting any other nation.</p>


<p>(z) shall not be false, inaccurate or misleading;</p>


<p>(aa) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the
dealing of which is prohibited or restricted in any manner under the provisions of any applicable law,
rule, regulation or guideline for the time being in force.
</p>

<p>(ab) shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our
internet service provider ("ISPs") or other suppliers;
</p>



<ul>
    <li>You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device,
program, algorithm or methodology, or any similar or equivalent manual process, to access,
acquire, copy or monitor any portion of the Platform or any Content, or in any way reproduce or
circumvent the navigational structure or presentation of the Platform or any Content, to obtain or
attempt to obtain any materials, documents or information through any means not purposely
made available through the Platform. We reserve Our right to bar any such activity</li>

<li>You shall not attempt to gain unauthorized access to any portion or feature of the Platform, or
any other systems or networks connected to the Platform or to any server, computer, network, or
to any of the services offered on or through the Platform, by hacking, password "mining" or any
other illegitimate means.</li>

<li>
    You shall not probe, scan or test the vulnerability of the Platform or any network connected to
the Platform nor breach the security or authentication measures on the Platform or any network
connected to the Platform. You may not reverse look-up, trace or seek to trace any information
on any other User of or visitor to Platform, or any other customer, including any account on the
Platform not owned by You, to its source, or exploit the Platform or any service or information
made available or offered by or through the Platform, in any way where the purpose is to reveal
any information, including but not limited to personal identification or information, other than Your
own information, as provided for by the Platform.
</li>


<li>
    You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about
Us or the brand name or domain name used by Us including the terms Allmart, Allmart.com, or
otherwise engage in any conduct or action that might tarnish the image or reputation, of Allmart
or sellers on platform or otherwise tarnish or dilute any Allmart's trade or service marks, trade
name and/or goodwill associated with such trade or service marks, trade name as may be
owned or used by us. You agree that You will not take any action that imposes an unreasonable
or disproportionately large load on the infrastructure of the Platform or Allmart's systems or
networks, or any systems or networks connected to Allmart.
</li>


<li>You agree not to use any device, software or routine to interfere or attempt to interfere with the
proper working of the Platform or any transaction being conducted on the Platform, or with any
other person's use of the Platform.</li>

<li>
    You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of
any message or transmittal You send to Us on or through the Platform or any service offered on
or through the Platform. You may not pretend that You are, or that You represent, someone else,
or impersonate any other individual or entity.
</li>


<li>
    You may not use the Platform or any content for any purpose that is unlawful or prohibited by
these Terms of Use, or to solicit the performance of any illegal activity or other activity which
infringes the rights of Allmart and / or others.
</li>


<li>
    You shall at all times ensure full compliance with the applicable provisions of the Information
Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and
also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign
Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales
Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies)
regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase,
and sale of products or services. You shall not engage in any transaction in an item or service,
which is prohibited by the provisions of any applicable law including exchange control laws or
regulations for the time being in force
</li>

<li>
    Solely to enable Us to use the information You supply Us with, so that we are not violating any
rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide,
perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the
copyright, publicity, database rights or any other rights You have in Your Information, in any
media now known or not currently known, with respect to Your Information. We will only use
Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the
Platform.

</li>


<li>From time to time, You shall be responsible for providing information relating to the products or
services proposed to be sold by You. In this connection, You undertake that all such information
shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of
such products or services so as to mislead other Users in any manner.
</li>

<li>You shall not engage in advertising to, or solicitation of, other Users of the Platform to buy or sell
any products or services, including, but not limited to, products or services related to that being
displayed on the Platform or related to us. You may not transmit any chain letters or unsolicited
commercial or junk email to other Users via the Platform. It shall be a violation of these Terms of
Use to use any information obtained from the Platform in order to harass, abuse, or harm
another person, or in order to contact, advertise to, solicit, or sell to another person other than Us
without Our prior explicit consent. In order to protect Our Users from such advertising or
solicitation, We reserve the right to restrict the number of messages or emails which a user may
send to other Users in any 24-hour period which We deems appropriate in its sole discretion.
You understand that We have the right at all times to disclose any information (including the
identity of the persons providing information or materials on the Platform) as necessary to satisfy
any law, regulation or valid governmental request. This may include, without limitation, disclosure
of the information in connection with investigation of alleged illegal activity or solicitation of illegal
activity or in response to a lawful court order or subpoena. In addition, We can (and You hereby
expressly authorize Us to) disclose any information about You to law enforcement or other
government officials, as we, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may
involve personal injury.</li>


</ul>


<p>We reserve the right, but have no obligation, to monitor the materials posted on the Platform. Allmart
shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to
violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this
right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU
POST ON THE PLATFORM AND IN YOUR PRIVATE MESSAGES. Please be advised that such
Content posted does not necessarily reflect Allmart views. In no event shall Allmart assume or have
any responsibility or liability for any Content posted or for any claims, damages or losses resulting
from use of Content and/or appearance of Content on the Platform. You hereby represent and
warrant that You have all necessary rights in and to all Content which You provide and all
information it contains and that such Content shall not infringe any proprietary or other rights of third
parties or contain any libellous, tortious, or otherwise unlawful information.
</p>


<ul>
    <li>
        Your correspondence or business dealings with, or participation in promotions of, advertisers
found on or through the Platform, including payment and delivery of related products or
services, and any other terms, conditions, warranties or representations associated with
such dealings, are solely between You and such advertiser. We shall not be responsible or
liable for any loss or damage of any sort incurred as the result of any such dealings or as the
result of the presence of such advertisers on the Platform.

    </li>
    
    <li>
        It is possible that other users (including unauthorized users or "hackers") may post or
transmit offensive or obscene materials on the Platform and that You may be involuntarily
exposed to such offensive and obscene materials. It also is possible for others to obtain
personal information about You due to your use of the Platform, and that the recipient may
use such information to harass or injure You. We do not approve of such unauthorized uses,
but by using the Platform You acknowledge and agree that We are not responsible for the
use of any personal information that You publicly disclose or share with others on the
Platform. Please carefully select the type of information that You publicly disclose or share
with others on the Platform.

    </li>
    
    <li>
        Allmart shall have all the rights to take necessary action and claim damages that may occur
due to your involvement/participation in any way on your own or through group/s of people,
intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).
    </li>
    
    <li>
        If you choose to browse or transact on the Platform using the voice command-based
shopping
feature, you acknowledge that Allmart and/or its affiliates will collect, store and use your voice
inputs on this feature to customize your experience and provide additional functionality as
well as to improve Allmart’s and/or its affiliates’ products and services. Allmart’s and/or its
affiliates’ use of your voice data will be in accordance with the Allmart Privacy Policy. You
accept that your use of this feature is restricted to the territory of the Republic of India. This
feature may not be accessible on certain devices and requires an internet connection.
Allmart reserves the right to change, enhance, suspend, or discontinue this feature, or any
part of it, at any time without notice to you. Your continued use of this feature constitutes
your acceptance of the terms related to this feature.
    </li>
    
    <li>
        You acknowledge and agree that the Hindi, Telugu, Tamil and Kannada translation features
are made available on the Platform on a reasonable effort basis for convenience only,
without any representation or warranties by Allmart, express or implied, including the
translations being error free, their accuracy, completeness or reliability. Under the translation
feature, You will have the option to add delivery addresses in the language selected by You
out of the featured languages. Such delivery addresses shall be transliterated in English
language for processing, handling and fulfilling Your orders on the Platform. Allmart
expressly disclaims any liability of any nature whatsoever arising from or related to the said
translation/transliteration features on the Platform. Some features and sections on the
Platform may not be translated in the language selected by You [Hindi, Telugu, Tamil or
Kannada language, as applicable], and the English version of the same will be the definitive
version. In the event of any conflict or inconsistency between the translated terms and the
English version available on the Platform, the English version on the Platform shall prevail.
This feature may not be accessible on certain devices. Allmart reserves the right to change,
enhance, suspend, or discontinue this feature, or any part of it, at any time without notice to
you.
    </li>
    
    
</ul>


<strong>Contents Posted on Platform</strong>

<p>All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music
and artwork (collectively, "Content"), is a third party user generated content and Allmart has no
control over such third party user generated content as Allmart is merely an intermediary for the
purposes of this Terms of Use.
</p>

<p>Except as expressly provided in these Terms of Use, no part of the Platform and no Content may be
copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated,
transmitted or distributed in any way (including "mirroring") to any other computer, server, Platform
or other medium for publication or distribution or for any commercial enterprise, without Allmart's
express prior written consent</p>


<p>You may use information on the products and services purposely made available on the Platform for
downloading, provided that You (1) do not remove any proprietary notice language in all copies of
such documents, (2) use such information only for your personal, non-commercial informational
purpose and do not copy or post such information on any networked computer or broadcast it in any
media, (3) make no modifications to any such information, and (4) do not make any additional
representations or warranties relating to such documents.</p>


<p>You shall be responsible for any notes, messages, emails, reviews, ratings, billboard postings,
photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or
information posted or transmitted to the Platform (collectively, "Content"). Such Content will become
Our property and You grant Us the worldwide, perpetual and transferable rights in such Content. We
shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law,
use the Content or any of its elements for any type of use forever, including but not limited to
promotional and advertising purposes and in any media whether now known or hereafter devised,
including the creation of derivative works that may include the Content You provide. You agree that
any Content You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct
on Site as mentioned herein, and You are not entitled to any payment or other compensation for
such use.</p>



<p>SOME CONTENT OFFERED ON THE PLATFORM MAY NOT BE SUITABLE FOR SOME
VIEWERS AND THEREFORE VIEWER DISCRETION IS ADVISED. ALSO, SOME CONTENT
OFFERED ON THE PLATFORM MAY NOT BE APPROPRIATE FOR VIEWERSHIP BY
CHILDREN. PARENTS AND/OR LEGAL GUARDIANS ARE ADVISED TO EXERCISE
DISCRETION BEFORE ALLOWING THEIR CHILDREN AND/OR WARDS TO ACCESS CONTENT
ON THE PLATFORM.</p>



<strong>Privacy</strong>

<p>We view protection of Your privacy as a very important principle. We understand clearly that You
and Your Personal Information is one of Our most important assets. We store and process Your
Information including any sensitive financial information collected (as defined under the Information
Technology Act, 2000), if any, on computers that may be protected by physical as well as
reasonable technological security measures and procedures in accordance with Information
Technology Act 2000 and Rules there under.Our current Privacy Policy is available at Privacy. Our
current Privacy Policy is available at Privacy. f You object to Your Information being transferred or
used in this way please do not use Platform. If You object to Your Information being transferred or
used in this way please do not use Platform.</p>



<p>
    
We may share personal information with our other corporate entities and affiliates. These entities
and affiliates may market to you as a result of such sharing unless you explicitly opt-out.</p>


<p>
    We may disclose personal information to third parties. This disclosure may be required for us to
provide you access to our Services, to comply with our legal obligations, to enforce our User
Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and
investigate fraudulent or illegal activities related to our Services. We do not disclose your personal
information to third parties for their marketing and advertising purposes without your explicit consent.
</p>


<p>
    We may disclose personal information if required to do so by law or in the good faith belief that such
disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process.
We may disclose personal information to law enforcement offices, third party rights owners, or others
in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy
Policy; respond to claims that an advertisement, posting or other content violates the rights of a third
party; or protect the rights, property or personal safety of our users or the general public.

</p>


<p>
    We and our affiliates will share / sell some or all of your personal information with another business
entity should we (or our assets) plan to merge with, or be acquired by that business entity, or
reorganization, amalgamation, restructuring of business. Should such a transaction occur that other
business entity (or the new combined entity) will be required to follow this privacy policy with respect
to your personal information.
</p>



<strong>Disclaimer of Warranties and Liability</strong>


<p>This Platform, all the materials and products (including but not limited to software) and services,
included on or otherwise made available to You through this site are provided on "as is" and "as
available" basis without any representation or warranties, express or implied except otherwise
specified in writing. Without prejudice to the forgoing paragraph, Allmart does not warrant that:</p>


<p>This Platform will be constantly available, or available at all; or</p>

<p>The information on this Platform is complete, true, accurate or non-misleading.
</p>

<p>
    Allmart will not be liable to You in any way or in relation to the Contents of, or use of, or otherwise in
connection with, the Platform. Allmart does not warrant that this site; information, Content, materials,
product (including software) or services included on or otherwise made available to You through the
Platform; their servers; or electronic communication sent from Us are free of viruses or other harmful
components. </p>


<p>
    Nothing on Platform constitutes, or is meant to constitute, advice of any kind. All the Products sold
on Platform are governed by different state laws and if Seller is unable to deliver such Products due
to implications of different state laws, Seller will return or will give credit for the amount (if any)
received in advance by Seller from the sale of such Product that could not be delivered to You.

</p>


<p>
    You will be required to enter a valid phone number while placing an order on the Platform. By
registering Your phone number with us, You consent to be contacted by Us via phone calls, SMS
notifications, mobile applications and/or any other electronic mode of communication in case of any
order or shipment or delivery related updates. We will not use your personal information to initiate
any promotional phone calls or SMS.
</p>


<strong>Selling</strong>

<p>As a registered seller, you are allowed to list item(s) for sale on the Platform in accordance with the
Policies which are incorporated by way of reference in this Terms of Use. You must be legally able
to sell the item(s) you list for sale on our Platform. You must ensure that the listed items do not
infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or
privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that
describe your item for sale. All listed items must be listed in an appropriate category on the Platform.
All listed items must be kept in stock for successful fulfilment of sales.
</p>

<p>The listing description of the item must not be misleading and must describe the actual condition of
the product. If the item description does not match the actual condition of the item, you agree to
refund any amounts that you may have received from the Buyer. You agree not to list a single
product in multiple quantities across various categories on the Platform. Allmart reserves the right to
delete such multiple listings of the same product listed by you in various categories.</p>


<strong>Services</strong>

<p>Payment</p>

<p>While availing any of the payment method/s available on the Platform, we will not be responsible or
assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You
due to:</p>

<ul>
    <li>Lack of authorization for any transaction/s, or</li>
    <li>Exceeding the preset limit mutually agreed by You and between "Bank/s", or</li>
    <li>Any payment issues arising out of the transaction, or</li>
    <li>Decline of transaction for any other reason/s</li>
</ul>


<p>All payments made against the purchases/services on Platform by you shall be compulsorily in
Indian Rupees acceptable in the Republic of India. Platform will not facilitate transactions with
respect to any other form of currency with respect to the purchases made on Platform.</p>

<p>Before shipping / delivering your order to you, Seller may request you to provide supporting
documents (including but not limited to Govt. issued ID and address proof) to establish the
ownership of the payment instrument used by you for your purchase. This is done in the interest of
providing a safe online shopping environment to Our Users</p>

<p>Further</p>

<ul>
    <li>Transactions, Transaction Price and all commercial terms such as Delivery, Dispatch of
products and/or services are as per principal to principal bipartite contractual obligations
between Buyer and Seller and payment facility is merely used by the Buyer and Seller to
facilitate the completion of the Transaction. Use of the payment facility shall not render
Allmart liable or responsible for the non-delivery, non-receipt, non-payment, damage, breach
of representations and warranties, non-provision of after sales or warranty services or fraud
as regards the products and /or services listed on Allmart's Platform. </li>

<li>
    You have specifically authorized Allmart or its service providers to collect, process, facilitate
and remit payments and / or the Transaction Price electronically or through Cash on Delivery
to and from other Users in respect of transactions through Payment Facility. Your
relationship with Allmart is on a principal to principal basis and by accepting these Terms of
Use you agree that Allmart is an independent contractor for all purposes, and does not have
control of or liability for the products or services that are listed on Allmart's Platform that are
paid for by using the Payment Facility. Allmart does not guarantee the identity of any User
nor does it ensure that a Buyer or a Seller will complete a transaction.
</li>

<li>
    You understand, accept and agree that the payment facility provided by Allmart is neither a
banking nor financial service but is merely a facilitator providing an electronic, automated
online electronic payment, receiving payment through Cash On Delivery, collection and
remittance facility for the Transactions on the Allmart Platform using the existing authorized
banking infrastructure and Credit Card payment gateway networks. Further, by providing
Payment Facility, Allmart is neither acting as trustees nor acting in a fiduciary capacity with
respect to the Transaction or the Transaction Price.

</li>

<p>Payment Facility for Buyers: </p>

<li>
    You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally
binding and enforceable contract with the Seller to purchase the products and /or services
from the Seller using the Payment Facility, and You shall pay the Transaction Price through
Your Issuing Bank to the Seller using Payment Facility.

</li>

<li>You, as a Buyer, may agree with the Seller through electronic communication and electronic
records and using the automated features as may be provided by Payment Facility on any
extension / increase in the Dispatch and/or Delivery time and the Transaction shall stand
amended to such extent. Any such extension / increase of Dispatch / Delivery time or
subsequent novation / variation of the Transaction should be in compliance with Payment
Facility Rules and Policies.</li>
<li>You, as a Buyer, shall electronically notify Payment Facility using the appropriate Allmart
Platform features immediately upon Delivery or non Delivery within the time period as
provided in Policies. Non notification by You of Delivery or non Delivery within the time
period specified in the Policies shall be construed as a deemed Delivery in respect of that
Transaction. In case of Cash On Delivery transactions, Buyer is not required to confirm the
receipt of products or services.</li>

<li>You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole
and exclusive remedy) in case You do not receive the Delivery within the time period agreed
in the Transaction or within the time period as provided in the Policies, whichever is earlier.
In case you do not raise a refund claim using Platform features within the stipulated time
than this would make You ineligible for a refund.</li>

<li>
    You, as a Buyer, understand that the Payment Facility may not be available in full or in part
for certain category of products and/or services and/or Transactions as mentioned in the
Policies and hence You may not be entitled to a refund in respect of the Transactions for
those products and /or services
</li>

<li>
    Except for Cash On Delivery transaction, refund, if any, shall be made at the same Issuing
Bank from where Transaction Price was received, or through any other method available on
the Platform, as chosen by You.

</li>

<li>
    For Cash On Delivery transactions, refunds, if any, will be made via electronic payment
transfers
</li>

<li>
    Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price
received in Indian Rupees.
</li>

<li>
    For electronics payments, refund shall be made through payment facility using NEFT / RTGS
or any other online banking / electronic funds transfer system approved by Reserve Bank
India (RBI).
</li>

<li>
    Refunds may be supported for select banks. Where a bank is not supported for processing
refunds, You will be required to share alternate bank account details with us for processing
the refund.

</li>

<li>
    Refund shall be conditional and shall be with recourse available to Allmart in case of any misuse by Buyer.
</li>

<li>
    We may also request you for additional documents for verification.
</li>

<li>
Refund shall be subject to Buyer complying with Policies.
</li>

<li>
    Allmart reserves the right to impose limits on the number of Transactions or Transaction
Price which Allmart may receive from on an individual Valid Credit/Debit/ Cash Card / Valid
Bank Account/ and such other infrastructure or any other financial instrument directly or
indirectly through payment aggregator or through any such facility authorized by Reserve
Bank of India to provide enabling support facility for collection and remittance of payment or
by an individual Buyer during any time period, and reserves the right to refuse to process
Transactions exceeding such limit.
</li>

<li>
    Allmart reserves the right to refuse to process Transactions by Buyers with a prior history of
questionable charges including without limitation breach of any agreements by Buyer with
Allmart or breach/violation of any law or any charges imposed by Issuing Bank or breach of
any policy.
</li>

<li>
    Allmart may do such checks as it deems fit before approving the receipt of/Buyers
commitment to pay (for Cash On Delivery transactions) Transaction Price from the Buyer for
security or other reasons at the discretion of Allmart. As a result of such a check if Allmart is
not satisfied with the credibility of the Buyer or genuineness of the Transaction or other
reasons at its sole discretion, Allmart shall have the right to reject the receipt of / Buyers
commitment to pay Transaction Price. For avoidance of doubt, it is hereby clarified that the
‘Cash on Delivery’ feature for payment, may be disabled for certain account users, at the
sole discretion of Allmart.
</li>

<li>
    Allmart may delay notifying the payment confirmation i.e. informing Seller to Dispatch, if
Allmart deems suspicious or for Buyers conducting high transaction volumes to ensure
safety of the Transaction and Transaction Price. In addition, Allmart may hold Transaction
Price and Allmart may not inform Seller to Dispatch or remit Transaction Price to law
enforcement officials (instead of refunding the same to Buyer) at the request of law
enforcement officials or in the event the Buyer is engaged in any form of illegal activity.
</li>

<li>
    The Buyer and Seller acknowledge that Allmart will not be liable for any damages, interests
or claims etc. resulting from not processing a Transaction/Transaction Price or any delay in
processing a Transaction/Transaction Price which is beyond control of Allmart.
</li>

<p>Compliance with Laws:</p>

<li>As required by applicable law, if the Customer makes a purchase of an amount equal to or
above INR 2 00 000.00, the Customer will be required to upload a scanned copy of his/her
PAN card on the Platform, within 4 days of making the purchase, failing which, the purchase
made by the Customer will be cancelled. The requirement to submit the PAN card arises
only once and if it has been submitted once by the Customer, it need not be submitted again.
The order of the Customer shall stand cancelled if there is a discrepancy between the name
of the Customer and the name on the PAN Card.
</li>

<li>
    Buyer and Seller shall comply with all the applicable laws (including without limitation Foreign
Exchange Management Act, 1999 and the rules made and notifications issued thereunder
and the Exchange Control Manual as may be issued by Reserve Bank of India from time to
time, Customs Act, Information and Technology Act, 2000 as amended by the Information
Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the
rules made there under, Foreign Contribution Regulation Act, 1976 and the rules made there
under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of
government of India) applicable to them respectively for using Payment Facility and Allmart
Platform.

</li>

<p>Buyer's arrangement with Issuing Bank: </p>

<li>
    All Valid Credit / Debit/ Cash Card/ and other payment instruments are processed using a
Credit Card payment gateway or appropriate payment system infrastructure and the same
will also be governed by the terms and conditions agreed to between the Buyer and the
respective Issuing Bank and payment instrument issuing company.
</li>
<li>
    All Online Bank Transfers from Valid Bank Accounts are processed using the gateway
provided by the respective Issuing Bank which supports the Payment Facility to provide
these services to the Users. All such Online Bank Transfers on Payment Facility are also
governed by the terms and conditions agreed to between Buyer and the respective Issuing
Bank.
</li>
</ul>

<br>
<p>Replacement/Guarantee/Warranty</p>

<p>Allmart does not take any responsibility of honouring and fulfilling the warranty, guarantee or replacement or quality or any promise for any product by the seller.</p>

<p>Damaged or defective or 'Not as described' products </p>


<p>If Allmart has any suspicion or knowledge that any of its buyers and sellers are involved in any
activity that is intended to provide claims or information that is false or not genuine, Allmart may also,
while reserving its rights to initiate civil and/or criminal proceedings against such member buyers and
sellers, at its sole discretion, suspend, block, restrict, cancel the Display Name of such buyers and
sellers and/or disqualify that user and any related users from availing protection through this
program. Customers who have been blocked for any suspicious or fraudulent activity on Allmart will
not be allowed to return their products.
</p>


<p>
    Allmart reserves its right to initiate civil and/or criminal proceedings against a user who files an
invalid and/or false claims or provides false, incomplete, or misleading information. In addition to the
legal proceedings as aforesaid, Allmart may at its sole discretion suspend, block, restrict, cancel the
Display Name [and its related Display Names] of such users and/or disqualify that user and any
related users from availing protection through this program. Any person who, knowingly and with
intent to injure, defraud or deceive, files a Fraudulent Complaint containing false, incomplete, or
misleading information may be guilty of a criminal offence and will be prosecuted to the fullest extent
of the law.

</p>


<p> Exchange Offers: </p>


<p>By participating in the exchange I confirm that I am the sole and absolute owner and/or user of the product mentioned above (device).</p>

<p>
    I confirm that the device which I am exchanging under the buyback program is genuine and is not
counterfeit, free from any and all encumbrances, liens, attachments, disputes, legal flaws, exchange
or any Agreement of Sale etc. and I have got the clear ownership of the said device.

</p>

<p>You agree to indemnity and keep indemnifying Allmart.com and any future buyer of the device
against all or any third party claims, demand, cost, expenses including attorney fees which may be
suffered, incurred, undergone and / or sustained by Allmart.com, its affiliates or any future buyer due
to usage of the device by you till date and you undertake to make good the same.

</p>

<p>
    I confirm that all the data in the said device will be erased before handing it over under the buy back
program. I also confirm that in spite of erasing the data manually/electronically, if any data is still
accessible due any technical reason, Allmart.com, Seller or the Manufacturer shall not be
responsible for the same and I will not approach Allmart.com for any retrieval of the data.

</p>

<p>
    I hereby give my consent that my personal information that I have provided in connection with this
buyback program might be processed, transferred and retained by the retailer and other entities
involved in managing the program for the purposes of validating the information that I provided
herein and for the administration of the program.

</p>

<p>
    I agree to indemnity and keep indemnifying the Allmart.com and any future buyer of the old device
against all or any third party claims, demand, cost, expenses including attorney fees which may be
suffered, incurred, undergone and / or sustained by Allmart.com, its affiliates or any future buyer due
to usage of the device by me till date and I undertake to make good the same.
</p>


<p>
    I understand once a device is sent by me to Allmart, in no scenario can this device be returned back
to me.
</p>
<p>
    I understand that the new device delivery and the old device pickup will happen simultaneously
(hand in hand) and I shall keep the old device ready to be given for exchange.
</p>


<p>
    Products distributed as gifts from state sponsored or NGO funded distribution programs are not
accepted for exchange under exchange offers.

</p>



<ol>
    <li>
        Limitation of liability: By using the Services, you agree that the liability of Allmart, its parents,
affiliates, related companies, officers, directors, employees, agents, representatives, partners
and licensors, shall be limited to the maximum extent permissible by applicable law. In no case
shall Allmart, its directors, officers, employees, affiliates, agents, contractors, principals, or
licensors be liable for any direct, indirect, incidental, punitive, special, or consequential damages
arising from your use of the Services or any Content or for any other claim related in any way to
your access to the Platform and/or use of the Services, including, but not limited to, any errors or
omissions in any Content or information on the Platform, or any loss or damage of any kind
incurred as a result of the use of the Services and/or reliance on any Content or information on
the Platform.

    </li>
    
    <li>Indemnification: You shall defend, indemnify and hold harmless Allmart its owners, affiliates,
subsidiaries, group companies, partners (as applicable), and their respective officers, directors,
agents, and employees (" Indemnified Parties"), from and against any claim, demand, damages,
obligations, penalty, losses or actions (including reasonable attorneys' fees) made by any third
party against the Indemnified Parties or imposed against the Indemnified Parties, due to or
arising out of your or your affiliate's or relative's: (a) breach of these Terms, the Privacy Policy
and/or any other policies; or (b) violation of any applicable law, rules, regulations; or (c) violation
of the rights (including infringement of intellectual property rights) of a third party or Allmart; or (d)
unauthorized, improper, illegal or wrongful use of your Allmart account (including by you or by
any person, including a third party, whether or not authorized or permitted by you). This
indemnification obligation will survive the expiry or termination of these Terms and/or your use of
the Service</li>

<li>Force Majeure: You agree that Allmart shall be under no liability whatsoever to you in the event
of non-availability of the Platform and/or any of the Services or any portion thereof, occasioned
by an Act of God, war, disease, revolution, riot, civil commotion, strike, lockout, flood, fire,
satellite failure, failure of any public utility, man-made disaster, satellite failure or any other cause
whatsoever beyond the control of Allmart (including any event which is caused by the failure or
non-performance on the part of the Content Owners or the Platform Partners).</li>

<li>
    Governing laws: These Terms shall be governed, interpreted, and construed in accordance with
the laws of India, without regard to the conflict of law provisions and for resolution of any dispute
arising out of your use of the Services or in relation to these Terms. Notwithstanding the
foregoing, you agree that (i) Allmart has the right to bring any proceedings before any
court/forum of competent jurisdiction and you irrevocably submit to the jurisdiction of such courts
or forum; and (ii) any proceeding brought by you shall be exclusively before the courts in
Bengaluru, India.

</li>



<li>
    Severability: If any provision of these Terms is held invalid, void, or unenforceable, then that
provision shall be considered severable from the remaining provisions, and the remaining
provisions shall be given full force and effect.
</li>


<li>
    Amendments: We may revise these Terms from time to time, without prior notice to you, to
update, revise, supplement, and otherwise modify these Terms and to impose new or additional
rules, policies, terms, or conditions on your use of the Service. Any updates, revisions,
supplements, modifications, and additional rules, policies, terms, and conditions will be posted
on the Platform and will be effective immediately after such posting and we recommend that you
periodically check these Terms on the Platform for such revised terms. Your continued use of the
Services and/or the Platform will be deemed to constitute your acceptance of any and all such
revised terms.

</li>

<li>
    Entire agreement: These Terms, the Privacy Policy and any other terms or policies as may be
prescribed by Allmart from time to time, constitute the entire agreement between you and
Allmart, which will govern your use of or access to the Services and/or the Platform, superseding
any prior agreements between you and Allmart regarding such use or access.
</li>


<li>
    Survival: You acknowledge that your representations, undertakings, and warranties and the
clauses relating to indemnities, limitation of liability, grant of license, governing law shall survive
the efflux of time and the termination of these Terms (including but not limited to Clauses 22 to
30 of these Terms).

</li>
</ol>


<p>Indemnity</p>

<p>You shall indemnify and hold harmless Allmart, its owner, licensee, affiliates, subsidiaries, group
companies (as applicable) and their respective officers, directors, agents, and employees, from any
claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty
imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies,
or Your violation of any law, rules or regulations or the rights (including infringement of intellectual
property rights) of a third party.
</p>


<p>Applicable Law</p>

<p>Terms of Use shall be governed by and interpreted and construed in accordance with the laws of
India. The place of jurisdiction shall be exclusively in Mumbai only. </p>


<p>Jurisdictional Issues/Sale in India Only </p>

<p>Unless otherwise specified, the material on the Platform is presented solely for the purpose of sale in
India. Allmart makes no representation that materials in the Platform are appropriate or available for
use in other locations/Countries other than India. Those who choose to access this site from other
locations/Countries other than India do so on their own initiative and Allmart is not responsible for
supply of products/refund for the products ordered from other locations/Countries other than India,
compliance with local laws, if and to the extent local laws are applicable.</p>


<strong> Trademark, Copyright and Restriction </strong>


<p>
    This site is controlled and operated by Allmart and products are sold by respective Sellers. All
material on this site, including images, illustrations, audio clips, and video clips, are protected by
copyrights, trademarks, and other intellectual property rights. Material on Platform is solely for Your
personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or
distribute such material in any way, including by email or other electronic means and whether
directly or indirectly and You must not assist any other person to do so. Without the prior written
consent of the owner, modification of the materials, use of the materials on any other Platform or
networked computer environment or use of the materials for any purpose other than personal,
non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is
prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a
commercial use for the purposes of this clause.
</p>


<p>Trademark complaint</p>

<p>Allmart respects the intellectual property of others. In case You feel that Your Trademark has been infringed, you can write to Allmart enquiry.allmart@gmail.com.</p>


<strong>Product Description </strong>

<p>Allmart we do not warrant that Product description or other content of this Platform is accurate,
complete, reliable, current, or error-free and assumes no liability in this regard. </p>


<strong>Limitation of Liability </strong>

<p>IN NO EVENT SHALL ALLMART BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR
CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE,
EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH
DAMAGES. </p>


<p>Contact Us </p>


<p>Please [contact us] for any questions or comments (including all inquiries unrelated to copyright
infringement) regarding this Platform.</p>


<p>Grievance officer</p>

<p>In accordance with Information Technology Act 2000 and rules made there under and the Consumer
Protection (E-Commerce) Rules, 2020, the name and contact details of the Grievance Officer are
provided below:</p>


<p>To: Grievance officer</p>
<p>Allmart Ecommerce LLP</p>
<p>Phone: 7710835444</p>
<p>Email: enquiry.allmart@gmail.com</p>
<p>Time: Mon - Sat (11:00 - 18:00 IST)</p>


<strong>POLICIES</strong>

<p>Profanity Policy</p>

<p>Allmart prohibits the use of language that is racist, hateful, sexual or obscene in nature in a public area.</p>

<p>This policy extends to text within listings, on Seller pages and all other areas of the site that another
User may view. If the profane words are part of a title for the item being sold, we allow Sellers to
'blur' out the bulk of the offending word with asterisks (i.e., s*** or f***).</p>

<p>Please report any violations of this policy to the correct area for review:</p>

<ul>
    <li>Report offensive Display Names</li>
    <li>Report offensive language in a listing or otherwise</li>
</ul>



<p>
    If a feedback comment; or any communication made between Users on the Platform; or email
communication between Users in relation to transactions conducted on Platform contain profanity,
please review Our feedback removal policy and submit a request for action/removal
</p>


<p>Disciplinary action may result in the indefinite suspension of a User's account, temporary
suspension, or a formal warning.</p>

<p>Allmart will consider the circumstances of an alleged policy violation and the user's trading records
before taking action.</p>

<p>Violations of this policy may result in a range of actions, including:</p>

<p>1. Limits placed on account privileges;</p>
<p>2. Loss of special status;</p>
<p>3. Account suspension.</p>


<p>Allmart shall have the right to delete a product review posted by the customer at its sole discretion, if
it is of the opinion that the review contains offensive language as stated above. Further, if Allmart is
of the opinion that the review unfairly either: (i) causes disadvantage to a product; or (ii) increases
the popularity of the product, Allmart shall have the right to delete the customer review. Allmart shall
also, at its sole discretion have the right to blacklist the customer from posting any further customer
reviews.
</p>



<p>Replacement Guarantee*</p>


<p>The Replacement Guarantee seeks to assist Buyers who have been defrauded by qualified sellers on the Platform. If at the time of delivery and/or within specified days from the date of delivery of the product/s, if any defect is found, then the buyer of the product/s can ask for replacement of the product/s from the seller.</p>

<p>If Allmart has suspicion or knowledge, that any of its buyers and sellers are involved in any activity
that is intended to provide claims or information that is false, misleading or not genuine, then Allmart
may while reserving its rights to initiate civil and/or criminal proceedings against User may also at its
sole discretion suspend, block, restrict, cancel the Display Name of such buyer and seller and /or
disqualify that User and any related Users from availing protection through this program.</p>


<p>
    Allmart reserves its right to initiate civil and/or criminal proceedings against a User who files an
invalid and/or false claims or provides false, incomplete, or misleading information. In addition to the
legal proceedings as aforesaid, Allmart may at its sole discretion suspend, block, restrict, cancel the
Display Name [and its related Display Names] of such User and/or disqualify that User and any
related Users from availing protection through this program. Any person who, knowingly and with
intent to injure, defraud or deceive, files a Fraudulent Complaint containing false, incomplete, or
misleading information may be guilty of a criminal offence and will be prosecuted to the fullest extent
of the law.

</p>


<p>Product returns and replacement shall only be as per the terms and policies of the seller. Allmart
plays no role and neither guarantees or warranties for anything.
</p>


<p>Disputes (Resolutions) Policy</p>


<p>Overview</p>


<p>Generally, transactions are conducted smoothly on Allmart. However there may be some cases
where both the Buyers and Sellers may face issues. At Allmart, we have a Dispute Resolution
process in order to resolve disputes between Buyers and Sellers.</p>


<p>What is a 'dispute'?</p>

<p>A 'Dispute' can be defined as a disagreement between a Buyer and a Seller in connection with a
transaction on the Platform.</p>


<p>How does a 'dispute' occur in the Marketplace?</p>


<p>Disputes are filed as a result of a disagreement between the Buyer and the Seller. Disputes arise out
of an issue that is raised by either party not being completely satisfied with the resolution of their
complaint/issue.</p>


<p>
    It is important that before a Buyer/Seller raises a dispute, they should attempt to solve the issue.
Please note that whenever a Buyer raises a dispute, the Seller's payment for that order is put on
hold immediately until the issue is resolved.
</p>

<p>How is a 'dispute' created?</p>


<p>
    Whenever there is a disagreement, the Buyer can write to us at enquiry.allmart@gmail.com, in order
to raise a dispute. Disputes can be raised at a particular transaction level.

</p>

<p>What are the various types of 'disputes'?</p>


<p>Following are the indicative examples of potential disputes:</p>

<p>1. Wrong item received</p>
<p>2. Item Not as described</p>
<p>3. Damaged or Seal broken on Product</p>
<p>4. Part/Accessory missing</p>
<p>5. Item not Compatible</p>
<p>6. Seller Description/Specification Wrong</p>
<p>7. Defective (Functional issues)</p>
<p>8. Product not working and Manufacturer claims invalid Invoice</p>



<p>In case the Seller rejects the return request of the Buyer, and Buyer raises a dispute, then Allmart
will try to mediate and resolve the dispute between both the parties. If the dispute is resolved in
favour of the Buyer, a refund is provided once the product is returned to the Seller. If the dispute is
settled in favour of the Seller, Buyer is entitled to any refund.
</p>


<p>When a dispute has been raised, Allmart may provide both the parties access to each others Display
Names, contact details including email addresses and other details pertaining to the dispute. Buyers
and Sellers are subject to final consent from Allmart for settling the dispute.</p>


<p>Raising disputes against Sellers does not automatically entitle the Buyer to a refund or replacement
for the product purchased. Allmart shall verify the disputes so raised and may process only such
claims that are valid and genuine.</p>


<p>Allmart shall at no point be responsible for any direct or indirect losses, expenses, costs of any
nature whatsoever that may be incurred by any Buyer/Seller.
</p>


<p>
    Claims of the nature of 'Buyer remorse' (i.e. instances where products are bought by the Buyer by
mistake or where the Buyer chooses to change his/her mind with regard to the product purchased by
him) will not be entertained through this program.
</p>


<p>
    Allmart reserves its right to initiate civil and/or criminal proceedings against a User who, files an
invalid and/or false claims or provides false, incomplete, or misleading information. In addition to the
legal proceedings as aforesaid, Allmart may at its sole discretion suspend, block, restrict, cancel the
Display Name [and its related Display Names] of such User and/or disqualify that user and any
related users from availing protection through this program.
</p>


<p>Allmart Customer Support Team may seek additional information / clarification from Buyer to
facilitate resolution of the dispute. In the event Buyer does not respond with information / clarification
sought within 10 days of such request, the dispute shall be auto-closed in favour of the Seller.</p>


<p>Disputes via Chargeback</p>


<p>Whenever a chargeback (CB) comes from a payment gateway/bank, following situations may arise:</p>

<ul>
    <li>Item not received CB - Buyer hasn't received the item. Refund will be created in accordance
with the dispute policies</li>
<li>
    Unauthorized CB - Buyer hasn't made this particular transaction. Refund will be created in
accordance with the dispute policies.
</li>


</ul>


<p>Seller expressly agrees that issuing the correct and complete invoice is the sole and primary
responsibility of the Seller. Furthermore, Seller shall ensure that invoices state "Powered by Allmart"
and failing to do so Seller will be liable for chargebacks (as applicable).</p>

<ul>
    <li>Item not as described - meaning item is not what Buyer expected. Dispute will be decided in
accordance with the dispute policies.</li>
</ul>


<p>Email Abuse & Threat Policy</p>

<p>Private communication, including email correspondence, is not regulated by Allmart. Allmart
encourages its Users to be professional, courteous and respectful when communicating by email.
</p>

<p>However, Allmart will investigate and can take action on certain types of unwanted emails that
violate Allmart policies.</p>

<p>Such instances:</p>

<p>Threats of Bodily Harm - Allmart does not permit Users to send explicit threats of bodily harm.
</p>


<p>Misuse of Allmart System - Allmart allows Users to facilitate transactions through the Allmart system,
but will investigate any misuse of this service.
</p>


<p>Spoof (Fake) email - Allmart will never ask you to provide sensitive information through email. In
case you receive any spoof (fake) email, you are requested to report the same to Us through the
'Contact Us' tab.</p>


<p>Spam (Unsolicited Commercial email) - Allmart's spam policy applies only to unsolicited commercial
messages sent by Allmart Users. Allmart Users are not allowed to send spam messages to other
Users.
</p>


<p>
    Offers to Buy or Sell Outside of Allmart - Allmart prohibits email offers to buy or sell listed products
outside of the Allmart Platform. Offers of this nature are a potential fraud risk for both Buyers and
Sellers.

</p>

<p>Allmart policy prohibits user-to-user threats of physical harm via any method including, phone, email
and on Our public message boards.</p>


<p>Violations of this policy may result in a range of actions, including:</p>


<ul>
    <li>Limits on account privileges.</li>
    <li>Account suspension.</li>
    <li>Cancellation of listings.</li>
    <li>Loss of special status.</li>
</ul>


<p>Other Businesses</p>

<p>Allmart does not take responsibility or liability for the actions, products, content and services on the
Platform, which are linked to Affiliates and / or third party Platforms using Platform's APIs or
otherwise. In addition, the Platform may provide links to the third party Platforms of Our affiliated
companies and certain other businesses for which, Allmart assumes no responsibility for examining
or evaluating the products and services offered by them. Allmart does not warrant the offerings of,
any of these businesses or individuals or the content of such third party Platform(s). Allmart does not
endorse, in any way, any third party Platform(s) or content thereof.</p>



<p>Note: In your notice of infringement, you shall be required to identify the individual listing which is
infringing your intellectual property. General notices shall not be accepted.
</p>


<p>We are happy to receive such information, but must advise that we may be limited in Our ability to
respond to your request absent formal notice from an authorized rights owner.</p>


<p>Notice of Infringement</p>

<p>Allmart Ecommerce LLP</p>
<p>_______________________</p>
<p>_______________________</p>

<p>I, [name] ____________________________ of [address] _________________________ do
solemnly and sincerely declare as follows:</p>


<p>1. I am the owner of certain intellectual property rights, said owner being named
__________________ ("IP Owner").
</p>


<p>2. I have a good faith belief that the item listings or materials identified in the annexure attached
hereto are not authorised by the above IP Owner, its agent, or the law and therefore infringe the
IP Owner's rights. Please expeditiously remove or disable access to the material or products
claimed to be infringing.</p>


<p>3. I may be contacted at:</p>


<p>Name ___________________________________________________________</p>
<p>Title & Company ________________________________________________________</p>
<p>Address _________________________________________________________</p>
<p>Email (correspondence) ___________________________________________________</p>
<p>Telephone/Fax _____________________________________________________________</p>
<p>Date _________________________________________________________________</p>
<p>and I make this declaration conscientiously believing it to be true and correct.</p>

<p>Declared by ______________________________</p>

<p>on [date] ___________________________________ in [place]________</p>


<p>Truthfully,</p>

<p>Signature</p>

<p>Addendum to Notice of Infringement:</p>

<p>List of Allegedly Infringing Listings, Products, or Materials</p>

<p>A Note on Reason Codes: When identifying item numbers please use the reasons below. When
removing products from the site, Allmart will inform Sellers of the specific reason for the removal of
their products.</p>


<p>
    Select the most appropriate reason. Please associate each item you report with only one reason
code.
</p>
<p>Trademark-infringement</p>


<p>1. Trademark owner doesn't make this type of product or has discontinued the production of the
product</p>

<p>2. Item(s) is an unlawful replica of a product made by the trademark owner or is counterfeit</p>


<p>Trademark-listing description infringement</p>
<p>1. Listing(s) has unlawful comparison to trademark owner's brand or product</p>
<p>2. Listing(s) contains unlawful use of trademark owner's logo
</p>

<p>Copyright-item infringement
</p>

<p>1. Software is being offered without any license or in violation of a license
</p>
<p>2. Item(s) is a bootleg recording;</p>
<p>3. Item(s) is an unlawful copy (software, games, movies, etc.);</p>
<p>4. Item(s) is unlawful duplication of printed material</p>
<p>5. Item(s) is an unlawful copy of other copyrighted work (paintings, sculptures, etc.)</p>


<p>Copyright-listing content infringement</p>

<p>1. Listing(s) comprises unauthorized copy of copyrighted text</p>
<p>2. Listing(s) comprises unauthorized copy of copyrighted image</p>
<p>3. Listing(s) comprises unauthorized copy of copyrighted image and text</p>


<p>Reason Code: _____________________________________________________________</p>

<p>Work(s)</p>

<p>infringed: _________________________________________________________</p>

<p>Item Number(s): ___________________________________________________________</p>

<p>Note</p>

<p>1. Please provide the ownership of Trademark (Trademark Registration Certificate should be in the
name of applicant)</p>

<p>2. Please provide the evidence as to the ownership of copyright.</p>


<p>All such Notices of Infringement shall be sent to enquiry.allmart@gmail.com.</p>

<p>
    Contacting the Seller

</p>


<p>At Allmart we are committed towards ensuring that disputes between sellers and buyers are settled
amicably by way of the above dispute resolution mechanisms and procedures. However, in the
event that a buyer wishes to contact the seller, he/ she may proceed to do so by accessing the seller
related information made available by the sellers on their product listing pages. Alternatively, the
buyers may also reach out to customer support at +91 7710835444 and write an email to
enquiry.allmart@gmail.com</p>






        <div class="dt-sc-hr-invisible-large"></div>

      </main>

<?php include('footer.php');?>